name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Core
  stacked: ^3.4.2
  stacked_services: ^1.4.0
  stacked_hooks: ^0.2.4

  ### CONFIG
  # For App Multiple Language Support
  easy_localization: ^3.0.5
  get_it: ^7.7.0
  injectable: ^2.5.0

  ### UTILITY
  easy_logger: ^0.0.2
  logger: ^2.1.0
  go_router: ^14.4.1

  ### NETWORK DEPENDENCIES
  # For App Networking
  dio: ^5.4.1
  
  # Responsive design
  flutter_screenutil: ^5.9.0
  i_toast: ^0.0.6
  i_updater: ^0.0.5
  ipagy: ^0.0.3
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.6

dependency_overrides:
  logger: ">=2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^1.6.0
  build_runner: ^2.4.5
  injectable_generator: ^2.6.2
  envied_generator: ^0.5.4+1
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
